[package]
name = "typewriter-app"
description = "A typewriter simulator for focused writing"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[[bin]]
name = "typewriter"
path = "src/main.rs"

[dependencies]
typewriter-core.workspace = true
eframe.workspace = true
anyhow.workspace = true
image.workspace = true

[build-dependencies]
image.workspace = true

[lints]
workspace = true
